def format_resume_report_email(
    email: str,
    job_role: str | None,
    analysis: dict
) -> dict:
    role_line = job_role if job_role else "General ATS Evaluation"

    subject = f"Your Resume ATS Report – Score {analysis['ats_score']}/100"

    body = f"""
Hello,

Here is your detailed resume analysis from ResumyZer.

Target Role:
{role_line}

----------------------------------
ATS SCORE
----------------------------------
{analysis['ats_score']} / 100

----------------------------------
OVERALL SUMMARY
----------------------------------
{analysis['overall_summary']}

----------------------------------
STRENGTHS
----------------------------------
""" + "\n".join(f"- {s}" for s in analysis["strengths"]) + """

----------------------------------
MISSING / WEAK AREAS
----------------------------------
""" + "\n".join(f"- {m}" for m in analysis["missing_or_weak_areas"]) + """

----------------------------------
ATS KEYWORD GAPS
----------------------------------
""" + "\n".join(f"- {k}" for k in analysis["ats_keyword_gaps"]) + """

----------------------------------
IMPROVEMENT SUGGESTIONS
----------------------------------
""" + "\n".join(f"- {i}" for i in analysis["improvement_suggestions"]) + """

----------------------------------
STRUCTURE FEEDBACK
----------------------------------
""" + "\n".join(f"- {f}" for f in analysis["structure_feedback"]) + f"""

----------------------------------
FINAL RECOMMENDATION
----------------------------------
{analysis['final_recommendation']}

----------------------------------

This report was generated by ResumyZer.
"""

    return {
        "to": email,
        "subject": subject,
        "body": body
    }
